kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: deploy
    image: alpine/git
    volumes:
      - name: apps
        path: /opt/infra/apps
      - name: sites
        path: /opt/infra/infra/sites
      - name: ssh
        path: /root/.ssh
      - name: docker-sock
        path: /var/run/docker.sock
      - name: docker-bin
        path: /usr/bin/docker
    commands:
      - cd /opt/infra/apps/bolao_copadomundo
      - git pull origin main
      - cd /opt/infra/infra/sites/bolao-site
      - docker compose build
      - docker compose up -d --force-recreate

volumes:
  - name: apps
    host:
      path: /opt/infra/apps
  - name: sites
    host:
      path: /opt/infra/infra/sites
  - name: ssh
    host:
      path: /root/.ssh
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-bin
    host:
      path: /usr/bin/docker
