kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: git-pull
    image: alpine/git
    volumes:
      - name: apps
        path: /opt/infra/apps
      - name: ssh
        path: /root/.ssh
    commands:
      - cd /opt/infra/apps/bolao_copadomundo
      - git pull origin main

  - name: docker-deploy
    image: docker:27-cli
    volumes:
      - name: sites
        path: /opt/infra/infra/sites
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - cd /opt/infra/infra/sites/bolao-site
      - docker compose build
      - docker compose up -d --force-recreate

volumes:
  - name: apps
    host:
      path: /opt/infra/apps
  - name: sites
    host:
      path: /opt/infra/infra/sites
  - name: ssh
    host:
      path: /root/.ssh
  - name: docker-sock
    host:
      path: /var/run/docker.sock
