version: "3.9"

services:
  backend:
    image: bolao-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5026:5000"
    environment:
      - FLASK_APP=backend.app
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/backend/data.db
    volumes:
      - ./backend:/app/backend
      - ./jogos_copa_2026.json:/app/jogos_copa_2026.json:ro
    restart: unless-stopped

  frontend:
    image: bolao-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "2626:80"

    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - backend
    restart: unless-stopped
